name: Speckle Automate

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Setup Nuget
        run: |
          dotnet nuget add source "https://gitlab.aurecongroup.com/api/v4/projects/714/packages/nuget/index.json" --name "Aurecon Package Manager" --username "${{ secrets.NUGET_USERNAME }}" --password "${{ secrets.NUGET_PASSWORD }}" --store-password-in-clear-text
          dotnet nuget list source
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-restore

      - name: Extract functionInputSchema
        id: extract_schema
        run: |
          dotnet run generate-schema ${HOME}/functionSchema.json
          cat ${HOME}/functionSchema.json

      - name: Speckle Automate Function - Build and Publish
        uses: specklesystems/speckle-automate-github-composite-action@0.7.2
        with:
          speckle_function_command: "dotnet SA-Function.dll"
          speckle_automate_url: https://automate.speckle.dev
          speckle_token: ${{ secrets.SPECKLE_FUNCTION_TOKEN }}
          speckle_function_id: ${{ secrets.SPECKLE_FUNCTION_ID }}
          speckle_function_input_schema_file_path: functionSchema.json
